metricbeat.modules:
  # Collect basic system metrics (CPU, memory, network, filesystem)
  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - filesystem
      - process
    enabled: true
    period: 10s

  # Collect metrics about Docker containers
  - module: docker
    metricsets: ["container", "cpu", "memory", "network", "diskio"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
