pipeline {
    agent any

    environment {
        def myString = "Hello, World!"
        def myNumber = 42
        def myBoolean = true
    }

    stages {
        stage('Print Variables') {
            steps {

                echo "String Variable: ${myString}"
                echo "Number Variable: ${myNumber}"
                echo "Boolean Variable: ${myBoolean}"
            }
        }
    }
}