version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass

  mysql:
    image: mysql:8.3
    container_name: my_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mongo_data:
  mysql_data:

