pipeline{
    agent any

    parameters {
        string(name: "deployEnv", defaultValue: "TEST", description: 'Which env to deploy?')
    }

    stages{
        stage("Demo"){
            steps{
                echo  "string is set to : ${params.deployEnv}"
            }
        }
    }
}