pipeline{

    agent any

    environment{
        IMAGE_NAME = "school_of_devops-nginx"
        IMAGE_TAG = "jenkins-${env.BUILD_ID}"
        HOST_PORT    = "80"
        CONTAINER_PORT = "80"
        CONTAINER_NAME = "schoolofdevops-jenkins-${env.BUILD_ID}"
        SITE_HOST    = "www.schoolofdevops.ro"
        SITE_URL     = "http://127.0.0.1"
    }
    stages{
        stage("Build Image"){
            steps{
                script {
                    docker.build("${IMAGE_NAME}:${IMAGE_TAG}", "-f Containers_SOD/nginx-alpine-site/Dockerfile Containers_SOD/nginx-alpine-site")
                    sh "docker images | grep ${IMAGE_NAME}"
                }
            }
        }
        stage("Run Container"){
            steps{
                script {
                    sh "docker run -d --name ${CONTAINER_NAME} -p ${HOST_PORT}:${CONTAINER_PORT} ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker ps | grep ${CONTAINER_NAME}"
                }
            }
        }
    }
}
