apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
