
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-ss
spec:
  serviceName: busybox
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: local-vol
          image: busybox:latest
          command:
            - 'sh'
            - '-c'
            - 'sleep 3600'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          volumeMounts:
            - name: data
              mountPath: /mnt/local
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 128Mi




