version: '3.8'

service:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /etc/nginx/certs
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - reverse_proxy_network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse_proxy_network

  schoolofdevops:
      image: schoolofdevops-nginx
      container_name: schoolofdevops-container
      restart: always
      expose:
        - "80"
      environment:
        - VIRTUAL_HOST=schoolofdevops.ro
        - LETSENCRYPT_HOST=schoolofdevops.ro
        - LETSENCRYPT_EMAIL=horodincarares@gmail.com
      networks:
        - reverse_proxy_network

networks:
  reverse_proxy_network:
    driver: bridge