name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add "bug" label to issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sS -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "User-Agent: gha" \
            https://api.github.com/repos/RaresHoro/School_Of_Devops/issues/4/labels \
            -d '{"labels":["bug"]}' \
          | jq .