name: Matrix Demo
on:
  push:
    branches:
      - main
    paths:
      - 'CI_CD_SOD/Github-Actions/Condition_Project/**'
      - '.github/workflows/matrix.yml'
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest, windows-latest]
        include:
            - node-version: 20
              operating-system: ubuntu-latest
        exclude:
            - node-version: 14
              operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        working-directory: "CI_CD_SOD/Github-Actions/Condition_Project"
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund