name: Reusable Deploy
on:
    workflow_call:
        inputs:
            artifact-name:
                required: false
                default: dist
                type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output info
        run: |
          echo "Deploying artifact: ${{ inputs.artifact-name }}"
          ls -la